<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LifeSaver.Domain\LifeSaver.Domain.csproj" />
    <ProjectReference Include="..\LifeSaver.Infrastructure\LifeSaver.Infrastructure.csproj" />
  </ItemGroup>

</Project>
