@LifeSaver_HostAddress = http://localhost:5204

POST {{LifeSaver_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "Test1234!"
}

###

POST {{LifeSaver_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "Test1234!"
}

###

GET {{LifeSaver_HostAddress}}/api/userProfile/1b540493-6ac1-470f-915b-e82d0789e6eb
Content-Type: application/json

###