name: Deploy API

on:
    push:
        branches:
            - main
        paths:
            - "api/**"
    workflow_dispatch:

defaults:
  run:
    working-directory: api

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4
    
            - name: Setup .NET 10
              uses: actions/setup-dotnet@v4
              with:
                dotnet-version: "10.x"
    
            - name: Restore dependencies
              run: dotnet restore
    
            - name: Build
              run: dotnet build --no-restore --configuration Release

            - name: Publish
              run: dotnet publish LifeSaver.API/LifeSaver.API.csproj --no-build --configuration Release --output ./publish

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                name: api
                path: api/publish