name: Deploy API

on:
    push:
        branches:
            - main
        paths:
            - "api/**"
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        defaults:
          run:
            working-directory: api

        steps:
            - name: Checkout
              uses: actions/checkout@v4
    
            - name: Setup .NET 10
              uses: actions/setup-dotnet@v4
              with:
                dotnet-version: "10.x"
    
            - name: Restore dependencies
              run: dotnet restore
    
            - name: Build
              run: dotnet build --no-restore --configuration Release

            - name: Publish
              run: dotnet publish LifeSaver.API/LifeSaver.API.csproj --no-build --configuration Release --output ./publish

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                name: api
                path: api/publish

    deploy:
        runs-on: ubuntu-latest
        needs: build
        permissions:
          id-token: write
          contents: read

        steps:
            - name: Download artifact
              uses: actions/download-artifact@v4
              with:
                name: api
                path: ./publish

            - name: Azure Login
              uses: azure/login@v2
              with:
                client-id: ${{ secrets.AZURE_CLIENT_ID }}
                tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

            - name: Set db connection string
              uses: azure/cli@v2
              with:
                azcliversion: latest
                inlineScript: |
                  az webapp config appsettings set \
                    --name app-life-saver \
                    --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
                    --settings ConnectionStrings__DbConnection="${{ secrets.DB_CONNECTION_STRING }}"

            - name: Deploy to Azure Web App
              uses: azure/webapps-deploy@v3
              with:
                app-name: app-life-saver
                package: ./publish